FROM node:20-bullseye

WORKDIR /app

COPY backend/package.json backend/package-lock.json* ./backend/
WORKDIR /app/backend

RUN npm install

COPY backend ./ 

RUN npx prisma generate

EXPOSE 4000

CMD ["npm", "start"]


